apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-event-dispatcher
  labels:
    app.kubernetes.io/name: cloud-event-dispatcher
    app.kubernetes.io/component: cloud-event-dispatcher
    app.kubernetes.io/part-of: ktwin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-event-dispatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-event-dispatcher
        app.kubernetes.io/component: cloud-event-dispatcher
        app.kubernetes.io/part-of: ktwin
    spec:
      containers:
        - name: cloud-event-dispatcher
          image: dev.local/ktwin/cloud-event-dispatcher:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
          env:
            - name: SERVICE_NAME
              value: cloud-event-dispatcher-1
            - name: PROTOCOL
              value: amqp
            - name: SERVER_URL
              value: rabbitmq
            - name: SERVER_PORT
              value: "5672"
            - name: USERNAME
              value: rabbitmq
            - name: PASSWORD
              value: rabbitmq
            - name: DECLARE_EXCHANGE
              value: "false"
            - name: DECLARE_QUEUE
              value: "false"
            - name: PUBLISHER_EXCHANGE
              value: amq.topic
            - name: SUBSCRIBER_QUEUE
              value: cloud-event-dispatcher-queue
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-event-dispatcher
  labels:
    app: cloud-event-dispatcher
spec:
  selector:
    app: cloud-event-dispatcher
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  type: ClusterIP